#!/bin/bash
# Deployment script for Mission Control Dashboard

set -e

echo "🚀 Mission Control Dashboard - Deployment Script"
echo ""
echo "STEP 1: Create GitHub Repository"
echo "=================================="
echo ""
echo "Run this command with your GitHub token:"
echo ""
echo "  export GH_TOKEN='<your-github-token-from-bitwarden>'"
echo "  gh repo create mission-control-dashboard \\"
echo "    --public \\"
echo "    --source=/Users/butler/.openclaw/workspace/mission-control-dashboard \\"
echo "    --remote=origin \\"
echo "    --push"
echo ""
echo "STEP 2: Get Render API Key"
echo "=========================="
echo ""
echo "From Bitwarden 'Developer' vault, get: RENDER_API_KEY"
echo ""
echo "STEP 3: Deploy to Render"
echo "======================="
echo ""
echo "1. Go to https://dashboard.render.com/new/web"
echo "2. Connect GitHub repository: mission-control-dashboard"
echo "3. Configure deployment:"
echo ""
echo "   Name: mission-control-dashboard"
echo "   Build Command: npm install && npm run build"
echo "   Start Command: npm start"
echo "   Environment:"
echo "     RENDER_API_KEY = <from-bitwarden>"
echo "     NODE_ENV = production"
echo ""
echo "4. Click Deploy"
echo ""
echo "STEP 4: Verify Deployment"
echo "========================="
echo ""
echo "Monitor at: https://dashboard.render.com"
echo "Dashboard will be live at: https://mission-control-dashboard.onrender.com"
echo ""
echo "---"
echo ""
echo "ℹ️  All code is ready, just need GitHub + Render setup!"
